### ISSUE TITLE
[BUG] Tabs pin themselves on their own

### ISSUE THREAD

**Issue by phoriah** [jayesh-bhoot/pin-unpin-tab#30]
How to reproduce:

1. Go to any big pages (big enough for scrollbar to appear), even some css files in this repository work as example
2. Click & Hold the scrollbar without moving it
3. The tab will pin / unpin itself depending on the current state

That's what happens to me personally.
It also happens on sites that are gallery-like, where there's a button to go to next image like in a slideshow and if you were to hold that button for long enough the site would pin / unpin itself.

This also causes another extension (https://github.com/dessant/search-by-image) to automatically pin all ShutterStock pages that it opens (not sure if it's the same issue as the one causing this but there's definitely something up with that too)

Note: this is pretty annoying and took me months to figure out what's causing it.

**Comment by jyssh** [comment]
> Click & Hold the scrollbar **without moving it**...The tab will pin / unpin itself depending on the current state

First things first: Long click (i.e., holding a left mouse click for a configurable amount of milliseconds) on non-interactive portions of a webpage to pin/unpin its tab is an add-on feature. You can disable it in the add-on preferences.

If you know that already, and your problem is only the long-click on a non-moving scrollbar, then read further.

Detecting a click on a scrollbar is not foolproof. Edge cases break it all the time. However, detecting a moving scrollbar is easy.

So, a long-click on a static scrollbar would trigger the pinning, but if the scrollbar is moved, then the trigger is cancelled.

Generally, scrollbar is clicked on in order to move it. So, I found it acceptable to not implement a buggy scrollbar detection, but instead treat a static scrollbar as one of the long-clickable areas of the webpage.

**Comment by jyssh** [comment]
> Note: this is pretty annoying and took me months to figure out what's causing it.

This is a valid concern. Perhaps, the whole problem wouldn't have bothered you much if there had been a "pinning/unpinning" indicator of sorts that appears on a long click.

May be animating the add-on icon close to the cursor to indicate the trigger could suffice. I will look into the feasibility.

**Comment by jyssh** [comment]
> That's what happens to me personally.
It also happens on sites that are gallery-like, where there's a button to go to next image like in a slideshow and if you were to hold that button for long enough the site would pin / unpin itself.

Long clicking on buttons should not trigger the add-on. Could you tell me the website on which this happened?

**Comment by jyssh** [comment]
> Any page that has a scrollbar, even this one. Video example below (note: all extensions but yours are disabled) https://github.com/jyssh/pin-unpin-tab/assets/95628489/ff164306-9139-400d-aead-5d14cd22911f

Could you please read *all* of my above responses first? The first response tries to address what you demonstrated in the above linked video.

**Comment by jyssh** [comment]
Go to the add-on's preferences.

If you untick the checkbox as shown in the screenshot below, then your problem should go away.

<img width="1171" alt="Screenshot 2023-07-27 at 8 48 07 PM" src="https://github.com/jyssh/pin-unpin-tab/assets/1915507/7b1cc564-75d1-4c1d-81bc-254ad2c0df59">
