### ISSUE TITLE
On-page click feature always triggered on X11 Linux

### ISSUE THREAD

**Issue by 2ion** [jayesh-bhoot/pin-unpin-tab#5]
I am using the latest version of the addon with Firefox Beta (59b8). The on-page click detection is overzealous when used from any pointing device with buttons I have available: Regardless of the interval setting on the preferences page, the pin/unpin action gets always triggered when clicking or tapping on a page, however long or short the click is. 

I've ruled out the touchpad-driver specific setting `ClickTime` which configures the length of the click (time between ButtonPress and ButtonRelease X11 events), which is set to 100ms and should be short enough NOT to trigger the feature -- doesn't matter. Likewise, physical clicks from touchpad or mouse report the correct time between ButtonPress and ButtonRelease events when monitored outside of Firefox.

So I assume there's something awry going on in Firefox or the extension, probably related to button event timing, or timestamp resolution? Let me know what information or tests I should provide/perform.

[about:support](https://gist.github.com/2ion/cc390ab607b04907cefd5f838abd073b) data.

**Comment by jayesh-bhoot** [comment]
I have pushed v3.2 that mitigates the following issues:

Bug fixes for long left-click approach:
- Now, the add-on is triggered only on long left mouse click/tap; operations through other mouse buttons are ignored.
- Add-on is not triggered when one or more of the modified keys (ctrl, alt, shift) are depressed. So, actions like ctrl+leftclick to open in new tab, shift+leftclick to open in new window, alt+leftpress to move the window can be carried out without hindrance.

Now, from what I understand by your description, this update would still not fix the time-interval issue. I don't have a clue as of now as to why the interval is being ignored. I will look into it tomorrow. Meanwhile, could you see if the updated add-on somehow fixes this issue too (as I believe it is related to what I fixed in v3.2)?

Let me know if v3.2 fixes the problem. Otherwise, I will look into it.

**Comment by 2ion** [comment]
Good morning and many thanks; https://github.com/jayesh-bhoot/pin-unpin-tab/commit/47edf7cd0fb3ac612b2ab16679b0f463eed4c0d6 fixes all the issues described in my first comment.
